[package]
name = "furcule-server"
description = "Local HTTP server that serves the Furcule viewer and a small REST and SSE API"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
furcule-core.workspace = true

[lints]
workspace = true
